config/routes.rb
DeviseOmniauth::Application.routes.draw do
  
  get "users/show"

  resources :authentications

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"},
    controllers: {omniauth_callbacks: 'authentications', registrations: 'registrations'},
    skip: [:registrations]
    as :user do
      get 'register', to: 'registrations#new', as: 'new_user_registration'
      post 'register', to: 'registrations#create', as: 'user_registration'
      delete 'register', to: 'registrations#destroy'
      get '/cancel', to: 'registrations#cancel', as: 'cancel_user_registration'
      get '/me/settings', to: 'registrations#edit',   as: 'edit_user_registration'
      put '/settings', to: 'registrations#update'
    end

  resources :users, :only => :show
  get "/:profile_url", to: 'users#show', as: 'profile'

  root :to => 'app_content#home'

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authentications, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :email, :password, :password_confirmation, :remember_me, :username

  def apply_omniauth(omni)
    authentications.build(:provider => omni['provider'],
                          :uid => omni['uid'],
                          :nickname => omni['info']['nickname'],
                          :name => omni['info']['name'],
                          :image => omni['info']['image'],
                          :token => omni['credentials'].token,
                          :token_secret => omni['credentials'].secret)
    if self.sign_in_count == 0
      import_first_auth
    end
  end

  def password_required?
    (authentications.empty? || !password.blank?) && super
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  private

  def import_first_auth
    self.name = authentications.first.name
    self.username = authentications.first.nickname
    self.image = authentications.first.image
    create_profile_url
  end

  def create_profile_url
    self.profile_url = '@' + username.downcase.strip.parameterize
  end

end

app/controllers/app_content_controller.rb
class AppContentController < ApplicationController
  def home
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController

  def index
    @authentications = current_user.authentications.all
  end

  def twitter
     omni = request.env["omniauth.auth"]
     authentication = Authentication.find_by_provider_and_uid(omni['provider'], omni['uid'])

     if authentication
       flash[:notice] = "Logged in Successfully"
       sign_in_and_redirect User.find(authentication.user_id)
     elsif current_user
       token = omni['credentials'].token
       token_secret = omni['credentials'].secret

       current_user.authentications.create!(:provider => omni['provider'], :uid => omni['uid'], :token => token, :token_secret => token_secret)
       flash[:notice] = "Authentication successful."
       sign_in_and_redirect current_user
     else
       user = User.new 
       user.apply_omniauth(omni)

       if user.save
         flash[:notice] = "Logged in."
         sign_in_and_redirect User.find(user.id)             
       else
         session[:omniauth] = omni.except('extra')
         redirect_to new_user_registration_path
       end
     end 
   end

  def destroy
     @authentication = Authentication.find(params[:id])
     @authentication.destroy
     redirect_to authentications_url, :notice => "Successfully destroyed authentication."
   end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def all
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in!"
      sign_in_and_redirect user, notice: "Signed in!"
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  def create
    super
    session[:omniauth] = nil unless @user.new_record?
  end
  
  def build_resource(*args)
      super
      if session[:omniauth]
        @user.apply_omniauth(session[:omniauth])
        @user.valid?
      end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def show
    @user = User.find_by_profile_url(params[:profile_url])
  end
end

app/helpers/app_content_helper.rb
module AppContentHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/app_content/Home.html.erb
<h1>AppContent#Home</h1>
<p>Find me in app/views/app_content/home.html.erb</p>

app/views/app_content/home.html.erb
<h1>AppContent#Home</h1>
<p>Find me in app/views/app_content/home.html.erb</p>

<% if user_signed_in? %>
	email: <%= current_user.email %>
	<br>
	authentication nickname: <%= current_user.authentications.first.nickname %>
	<br>
	Username: <%= current_user.username %>
	<br>
	Profile URL: <%= current_user.profile_url %>
	<br>
	Sign in count: <%= current_user.sign_in_count %>


<% else %>
	Nobody signed in
<% end %>

app/views/app_content/newhome.html.erb
<h1>AppContent#Home</h1>
<p>Find me in app/views/app_content/home.html.erb</p>

app/views/authentications/create.html.erb
<h1>Authentications#create</h1>
<p>Find me in app/views/authentications/create.html.erb</p>

app/views/authentications/destroy.html.erb
<h1>Authentications#destroy</h1>
<p>Find me in app/views/authentications/destroy.html.erb</p>

app/views/authentications/index.html.erb
<h1>Authentications#index</h1>
<p>Find me in app/views/authentications/index.html.erb</p>

<!-- Destroy authentications works for now, but we only want to use one so no point in allowing -->
<!-- 
<% if @authentications %>
  <% unless @authentications.empty? %>
    <p><strong>You can sign in to this account using:</strong></p>
    <div class="authentications">
      <% for authentication in @authentications %>
        <div class="authentication">
          <div class="uid"><%= authentication.provider %></div>
          <%= link_to "X", authentication.destroy, :class => "remove" %> 
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  <% end %>
  <p><strong>Add another service to sign in with:</strong></p>
<% else %>
  <p><strong>Sign in through one of these services:</strong></p>
<% end %>
 -->
<%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DeviseOmniauth</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
</head>
<body>

  <div id="container">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to 'Authentications', authentications_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %>
    <% end %>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>

    <%= yield %>

  </div>

</body>

</html>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>